# Generated by Django 5.0.1 on 2024-01-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_hotel_inventoryitem_orderitem_purchaseorder_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
